[package]
name = "tmp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.89"
candid = "0.10.19"
clap = { version = "4.5.42", features = ["derive"] }
ic-agent = "0.44.2"
thiserror = "2.0.17"
mockall = "0.13.1"
tokio = { version = "1.20", features = ["full"] }
